export interface FAQItem {
    question: string;
    answer: string;
}

export const faqItems: FAQItem[] = [
    {
        question: 'What is Upshift?',
        answer: 'Upshift is an all-in-one productivity app that helps you transform your life from the bottom up.'
    },
    {
        question: 'is there an Android version?',
        answer: 'Yes, we are working on it. Join the waitlist to get notified when it\'s ready!'
    },
    {
        question: 'What is the Quest Blocker?',
        answer: 'Quest Blocker is our unique feature that blocks distracting apps until you complete your daily quests. It\'s a powerful motivator to get your important tasks done first before accessing entertainment apps.'
    },
    {
        question: 'What is the difference between Quests and Sidequests?',
        answer: 'Quests are your main daily habits you want to build long-term. Sidequests are daily challenges generated by app, offering extra XP and keeping things interesting. Complete sidequests for bonus rewards and variety!'
    },
    {
        question: 'Can I trust you with my screen time data?',
        answer: "You don't have to! Upshift is built on top of Apple's Screen Time technology. Apple built it with privacy in mind so we can't view your screen time even if it wanted to."
    },
    {
        question: 'Is there a free version of Upshift?',
        answer: 'Upshift offers 7 days of free trial, to show you why this is the app you were looking for :)'
    },
    {
        question: 'What is the Affiliate Program?',
        answer: 'Share Upshift with others and earn rewards through our Affiliate Program. When people sign up using your referral code/username, you earn credits that can be used to redeem bunch of rewards.'
    }
];
